csharp
public partial class SaleOrder {
    public int MrpProductionCount { get; set; }
    public List<MrpProduction> MrpProductionIds { get; set; }

    public void ComputeMrpProductionIds() {
        var data = Env.Get("ProcurementGroup").ReadGroup(
            new List<object> {
                new { sale_id = new List<int> { this.Id } }
            },
            new List<string> { "sale_id" },
            new List<string> { "id:recordset" }
        );

        var mrpProductions = new Dictionary<int, List<MrpProduction>>();
        foreach (var item in data) {
            var saleId = (int)item["sale_id"];
            var procurementGroups = (List<ProcurementGroup>)item["id:recordset"];
            mrpProductions[saleId] = procurementGroups.StockMoveIds.CreatedProductionId.ProcurementGroupId.MrpProductionIds.Union(procurementGroups.MrpProductionIds).ToList();
        }

        var mrpProductionIds = mrpProductions.ContainsKey(this.Id) ? mrpProductions[this.Id] : Env.Get<MrpProduction>().Search(new List<object>() { });
        this.MrpProductionCount = mrpProductionIds.Count;
        this.MrpProductionIds = mrpProductionIds;
    }

    public ActionViewMrpProduction() {
        var action = new Dictionary<string, object> {
            { "res_model", "Mrp.Production" },
            { "type", "ir.actions.act_window" }
        };

        if (this.MrpProductionIds.Count == 1) {
            action.Add("view_mode", "form");
            action.Add("res_id", this.MrpProductionIds[0].Id);
        } else {
            action.Add("name", $"Manufacturing Orders Generated by {this.Name}");
            action.Add("domain", new List<object> {
                new { id = new List<int> { this.MrpProductionIds.Select(p => p.Id).ToList() } }
            });
            action.Add("view_mode", "tree,form");
        }

        return action;
    }
}
